# This config is required for Prometheus to scrape other containers
scrape_configs:
- job_name: ipfs-background-service
  static_configs:
  - targets: 
    - server:9091
    labels:
      service: ipfs-background-service
      endpoint: server-metrics
  - targets: 
    - worker:9081
    labels:
      service: ipfs-background-service
      endpoint: worker-metrics
